### ISSUE TITLE
Works with source("Install-VisionEval.R"), but not .bat

### ISSUE THREAD

**Issue by dflynn-volpe** [jrawbits/VisionEval-install#1]
On Windows 7:
![image](https://user-images.githubusercontent.com/9107903/48779286-4703f200-eca5-11e8-8b40-35d9b48d96da.png)

Installing from within R, by sourcing Install-VisionEval.R does work... Rtools is in my Windows PATH, so not sure why `Rscript` fails here

Convenience functions are nice:

- `verspm()` fails on `Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :`
- `verrpat()` works great
- `vegui()` is having some of the same readModelState() issues as over in the add_scenarios branch, but these should now be fixed, e.g. `Warning: Error in readModelState: object 'i' not found`

**Comment by jrawbits** [comment]
Rscript is part of R itself, not Rtools, so you need your R bin directory on the path.  You only need Rtools to build the installers, not to install.

Other points:  the directory structure of RSPM changed in the add_scenario branches; I'll get that updated shortly, plus I'll dust up VEGUI to see if they have fixed the problems.

**Comment by jrawbits** [comment]
I think it's working now.  If you could verify and/or close the issue (or provide another error report) it will be much appreciated.

**Comment by dflynn-volpe** [comment]
Super. I added C:\Program Files\R\R-3.5.1\bin to the PATH ([followed this recipe](http://www.rap.ucar.edu/staff/ericg/RWinBuild.html)) and it now works.

![image](https://user-images.githubusercontent.com/9107903/49111862-5532af00-f25f-11e8-9d20-3bbb6498e866.png)
